# Generated by Django 2.1 on 2019-08-23 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetallelPrestamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Ejemplar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroejemplar', models.CharField(max_length=45)),
                ('fechadecompra', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=45)),
                ('isbn', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaprestamo', models.DateField()),
                ('nombrecliente', models.CharField(max_length=45)),
                ('telefonocliente', models.CharField(max_length=45)),
                ('estado', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='ejemplar',
            name='Libro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.Libro'),
        ),
        migrations.AddField(
            model_name='detallelprestamo',
            name='Ejemplar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.Ejemplar'),
        ),
        migrations.AddField(
            model_name='detallelprestamo',
            name='Prestamo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.Prestamo'),
        ),
    ]
