# Generated by Django 2.1 on 2019-08-29 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallelprestamo',
            name='fechadevolucion',
            field=models.DateField(null=True, verbose_name='Fecha de Devolucion'),
        ),
    ]
